---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replicate.jnytnai0613.github.io
  resources:
  - clusterdetectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replicate.jnytnai0613.github.io
  resources:
  - clusterdetectors/finalizers
  verbs:
  - update
- apiGroups:
  - replicate.jnytnai0613.github.io
  resources:
  - clusterdetectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - replicate.jnytnai0613.github.io
  resources:
  - replicators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replicate.jnytnai0613.github.io
  resources:
  - replicators/finalizers
  verbs:
  - update
- apiGroups:
  - replicate.jnytnai0613.github.io
  resources:
  - replicators/status
  verbs:
  - get
  - patch
  - update
